### ISSUE TITLE
 When I compile shellinabox binary file, always prompt make not through, tried a lot of ways, you can publish the binary file?

### ISSUE THREAD

**Issue by libn-net** [gerco/shellinabox-alpine#1]
@gerco 👍 

Such as title
The compiler took me a long time, hope you can provide, thank you !

**Comment by mvandenabeele** [comment]
I know this is an old issue and a project that is probably abandoned, but I too would like to know what to do to get it compiled again. I don't mind helping and/or testing but I'm more of a Windows c++ programmer, just getting my feet wet in the Linux world.

**Comment by gerco** [comment]
This project was created before Docker supported multi-stage builds. I tried to refactor the build, but sadly, shellinabox has been abandoned and no longer compiles due to its dependencies having moved on. It depends on old openssl versions that should no longer be used and doesn't compile with anything vaguely recent.

I recommend looking at https://hub.docker.com/r/wettyoss/wetty for a replacement.
